In [30]:
import numpy as np

## DataTypes & Attributes

In [31]:
# NumPy's main datatype is nndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [32]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a1.shape

(3,)

In [34]:
a2.shape

(2, 3)

In [35]:
a3.shape

(2, 3, 3)

In [36]:
a1.size

3

In [37]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2.Creating arrays

In [38]:
sample_array = np.array([1,2,3])

In [39]:
sample_array

array([1, 2, 3])

In [40]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [42]:
random_array = np.random.randint(0,10,size=(3,5))

In [43]:
random_array

array([[6, 5, 1, 7, 1],
       [1, 8, 7, 8, 2],
       [0, 6, 2, 3, 6]])

In [44]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.29171719, 0.37396809, 0.1501882 ],
       [0.12472146, 0.79624784, 0.22628536],
       [0.29935094, 0.37889429, 0.92906148],
       [0.98947027, 0.27063737, 0.48112397],
       [0.1154997 , 0.93076796, 0.51005889]])

In [45]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.01551263, 0.29722368, 0.2882741 ],
       [0.1265637 , 0.99728886, 0.7503739 ],
       [0.13453299, 0.10063569, 0.13766161],
       [0.77975764, 0.11327068, 0.40462041],
       [0.6775895 , 0.12546436, 0.24876368]])

In [46]:
# Pseudo - random numbers
#np.random.seed()
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 2, 2],
       [4, 1, 9],
       [7, 0, 5],
       [8, 1, 1],
       [5, 8, 2]])

## 3.Viewing arrays and matrices

In [47]:
np.unique(random_array)

array([0, 1, 2, 3, 5, 6, 7, 8])

In [48]:
a1

array([1, 2, 3])

In [49]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a1[0]

1

In [52]:
a2[0]

array([1. , 2. , 3.3])

In [53]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[2, 4, 0, 6, 2],
         [4, 3, 2, 9, 1],
         [9, 7, 6, 5, 6],
         [4, 3, 0, 8, 5]],

        [[8, 5, 4, 5, 1],
         [8, 9, 9, 3, 7],
         [0, 2, 6, 3, 8],
         [7, 7, 9, 4, 8]],

        [[0, 6, 9, 6, 2],
         [3, 1, 8, 1, 6],
         [5, 7, 0, 5, 0],
         [7, 6, 0, 0, 5]]],


       [[[4, 4, 0, 4, 9],
         [4, 2, 4, 9, 2],
         [3, 4, 9, 0, 4],
         [0, 4, 7, 6, 9]],

        [[3, 0, 8, 2, 7],
         [8, 3, 2, 9, 7],
         [0, 7, 1, 3, 4],
         [8, 6, 6, 7, 2]],

        [[6, 3, 2, 1, 6],
         [9, 9, 8, 0, 7],
         [3, 1, 1, 3, 1],
         [3, 0, 5, 4, 0]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[2, 4, 0, 6],
         [4, 3, 2, 9],
         [9, 7, 6, 5],
         [4, 3, 0, 8]],

        [[8, 5, 4, 5],
         [8, 9, 9, 3],
         [0, 2, 6, 3],
         [7, 7, 9, 4]],

        [[0, 6, 9, 6],
         [3, 1, 8, 1],
         [5, 7, 0, 5],
         [7, 6, 0, 0]]],


       [[[4, 4, 0, 4],
         [4, 2, 4, 9],
         [3, 4, 9, 0],
         [0, 4, 7, 6]],

        [[3, 0, 8, 2],
         [8, 3, 2, 9],
         [0, 7, 1, 3],
         [8, 6, 6, 7]],

        [[6, 3, 2, 1],
         [9, 9, 8, 0],
         [3, 1, 1, 3],
         [3, 0, 5, 4]]]])

In [56]:
a4[:,:,:,:2]

array([[[[2, 4],
         [4, 3],
         [9, 7],
         [4, 3]],

        [[8, 5],
         [8, 9],
         [0, 2],
         [7, 7]],

        [[0, 6],
         [3, 1],
         [5, 7],
         [7, 6]]],


       [[[4, 4],
         [4, 2],
         [3, 4],
         [0, 4]],

        [[3, 0],
         [8, 3],
         [0, 7],
         [8, 6]],

        [[6, 3],
         [9, 9],
         [3, 1],
         [3, 0]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [57]:
a1

array([1, 2, 3])

In [58]:
ones

NameError: name 'ones' is not defined

In [ ]:
ones = np.ones(3)

In [ ]:
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * ones

In [ ]:
a2

In [ ]:
a1 * a2

In [ ]:
# How can you reshape a2 to be compatible with a3?
a2 * a3

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decmals
a2 // a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

In [ ]:
list_list = [1,2,3]
type(list_list)

In [ ]:
sum(list_list)

In [ ]:
a1

In [ ]:
# Use Pyhton's ,ethods on Python datatypes and use
# NumPy's methods on NyPums arrays

In [ ]:
massive_array = np.random.random(100000)

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
np.std(a2)

In [ ]:
# Varioace = measure of the average degree to which each number is difference
# Higher variance = wider range of numbers
# Lower variance  = lower range of numbers

# measure spread of data, between each cell
np.var(a2)

In [ ]:
# Demo of std and var
higher_var_array = np.array([1,100,200,300,400,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(higher_var_array), np.var(low_var_array)

In [ ]:
np.std(higher_var_array), np.std(low_var_array)

In [ ]:
np.mean(higher_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(higher_var_array)
plt.show()

### Reshaping & trtansposing

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2.reshape(2,3,1).shape

In [ ]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
# Transpose = switches the axis'
a2.T

In [ ]:
a2.shape, a2.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

In [ ]:
mat2

In [ ]:
mat1 * mat2

In [ ]:
mat3 = np.dot(mat1,mat2.T)
mat3

In [ ]:
mat3.shape

In [ ]:
np.random.seed()
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tue","Wen","Thurs","Frid"],columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

In [ ]:
# Create prices array
prices = np.array([10,8,12])

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"],columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

In [ ]:
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
weekly_sales

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sales

In [ ]:
 weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

### Comparison Operators

In [ ]:
a1

In [ ]:
a2

In [59]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [60]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

### 5.Sorting arrays

In [62]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[2, 5, 9, 9, 5],
       [0, 7, 7, 6, 3],
       [4, 9, 8, 4, 3]])

In [63]:
np.sort(random_array)

array([[2, 5, 5, 9, 9],
       [0, 3, 6, 7, 7],
       [3, 4, 4, 8, 9]])

In [65]:
# Sort by the index'
np.argsort(random_array)

array([[0, 1, 4, 2, 3],
       [0, 4, 3, 1, 2],
       [4, 0, 3, 2, 1]], dtype=int64)

In [66]:
a1
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [67]:
a1

array([1, 2, 3])

In [68]:
np.argmin(a1)

0

In [69]:
np.argmax(a1)

2

In [71]:
np.argmax(random_array, axis=0)

array([2, 2, 0, 0, 0], dtype=int64)

In [72]:
np.argmax(random_array, axis=1)

array([2, 1, 1], dtype=int64)

### 6. Practical Example - NumPy in Action

<img src="panda.png" />

In [79]:
# Turn an image into a NmumPy array
from matplotlib.image import imread

panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [80]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [81]:
panda.size, panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)